function d =  plot_positions(mat_file)
% Plot XY trajectories for each tracked fish.
% mat_file = '~/intermediate/2026-01-24_04-56/recordings/positions_n8.mat';
% This is currently set for 18 fish. Need to edit code...
% Last plot gets electrode positions

% Load data from Matlab file generated by 
d = load(mat_file);

% d.idents    : (n_fish,)
% d.times     : (n_times,)
% d.x_ident   : (n_fish, n_times)  — NaN where no data
% d.y_ident   : (n_fish, n_times)

n_fish = length(d.idents); # How many fish
colors = lines(n_fish);   % Distinct colors for each fish

figure('Name', 'Fish XY positions', 'Color', 'w');

for k = 1:n_fish
    x = d.x_ident(k, :);
    y = d.y_ident(k, :);

    % Only plot where data exists
    valid = ~isnan(x) & ~isnan(y);
    if ~any(valid)
        continue
    end

    subplot(6,4,k); hold on;
    plot(x(valid), y(valid), '-o', ...
        'Color',           colors(k, :), ...
        'MarkerFaceColor', colors(k, :), ...
        'MarkerSize',      3, ...
        'LineWidth',       1, ...
        'DisplayName',     sprintf('fish %.0f (%.0f Hz)', d.idents(k), ...
                                   mean(d.fund_v(d.ident_v == d.idents(k)), 'omitnan')));
end

% Arena outline
arena_x = [0, 250, 250, 0, 0];   % cm — adjust if needed
arena_y = [0, 0, 2*50*sqrt(3)/2, 2*50*sqrt(3)/2, 0];
plot(arena_x, arena_y, 'k--', 'LineWidth', 1.5, 'HandleVisibility', 'off');

% Electrode positions for reference

ydist = 50 * sqrt(3) / 2;
XY = [125, 0; 175, 0; 25, 0; 75, 0; 100, ydist; 150, ydist; ...
      200, ydist; 225, 0; 0, ydist; 50, ydist; 225, 2*ydist; ...
      250, ydist; 125, 2*ydist; 175, 2*ydist; 25, 2*ydist; 75, 2*ydist];
scatter(XY(:,1), XY(:,2), 60, 'k', '^', 'filled', 'HandleVisibility', 'off');
for e = 1:16
    text(XY(e,1), XY(e,2) + 3, sprintf('%02d', e-1), ...
        'HorizontalAlignment', 'center', 'FontSize', 7, 'Color', [0.4 0.4 0.4]);
end

axis equal;
grid on;
xlabel('x (cm)');
ylabel('y (cm)');

% title(sprintf('Fish trajectories  (n = %d fish)', n_fish));
% legend('show', 'Location', 'bestoutside');

hold off;

